server:
  port: "8888"

database:
  dsn: "root:Jinke@.123@tcp(10.0.1.141:3307)/taskdb?charset=utf8mb4&parseTime=True&loc=Local"
  logSQL: true
  logLevel: "info"

log:
  level: "info"
  filename: "/Users/jacklondon/go/logs/20060102.log"
  maxSize: 1  # 日志文件大小，现在设置为1
  maxSizeUnit: "M"  # 单位改为M，表示1MB
  maxBackups: 10
  maxAge: 28
  compress: false